chore!: Normalize repository, dropping node <10.13 support
gulpjs/remove-bom-stream pull request #3
Opened 2021-12-25 09:40 UTC by sttk

This PR updates this project:

- Updates dependency versions
- Update GitHub Actions files
- Adds, changes and deletes some project files

2021-12-29 01:26 UTC, phated commented on LICENSE
> +Copyright (c) 2017, 2021 Blaine Bublitz <blaine.bublitz@gmail.com>, Eric Schoffstall <yo@contra.io>
```suggestion
Copyright (c) 2017, 2021 Blaine Bublitz <blaine.bublitz@gmail.com> and Eric Schoffstall <yo@contra.io>
```

2021-12-29 01:27 UTC, phated commented on package.json
> +    "safe-buffer": "^5.2.1",
We'll want to drop safe-buffer completely, it was a holdover for the old buffer support

2021-12-29 01:27 UTC, phated requested changes
Sorry, I should have done this as a review. We want to remove safe-buffer in this change.

2022-01-08 06:37 UTC, sttk commented
@phated I've removed `safe-buffer`. Please review this PR again.

2022-01-10 00:16 UTC, phated approved these changes
Thanks @sttk! I also opened #4 and #5 for follow ups before we release this next version.

2022-01-10 00:17 UTC, merged